### ISSUE TITLE
Authenticate with API app code instead of a real user

### ISSUE THREAD

**Issue by GanimanSwift** [lord-kyron/terraform-provider-phpipam#38]
I cannot seem to authenticate with an "app code" and this provider only works with a real user account. Is there is way to make this work? According to PHPIPAM docs this functionality called "static authentication" was added in version 1.4. "App security" set to "SSL with App code token" only ever returns "Error logging into PHPIPAM: Error from API (401): Unauthorized".

**Comment by bahramsabri** [comment]
@pavel-z1 Are you going to add this fanctionality soon?

**Comment by meisterfischy** [comment]
Right now the phpipam-sdk-go does not support static app code authentication. I created a [pull request](https://github.com/pavel-z1/phpipam-sdk-go/pull/9), which enables this feature: If one leaves the username empty, it will use the password as the static api app code. As soon as it will be merged, I will create a pull request to bump the version, since no more changes are required to make it work.

**Comment by lord-kyron** [comment]
@meisterfischy - it seems it was merged. Are you going to add another pull request?

**Comment by rocketnateynate** [comment]
I am having the same issue still, and am on 1.4.
